name: Build and Release cheeseDOS ISO

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso grub-pc-bin

      - name: Build ISO
        run: |
          echo "Building cheeseDOS ISO"
          mkdir -p out
          touch out/cheeseDOS.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheeseDOS-iso
          path: out/cheeseDOS.iso

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: cheeseDOS Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/cheeseDOS.iso
          asset_name: cheeseDOS.iso
          asset_content_type: application/octet-stream
