name: Build and Release cheeseDOS ISO

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso grub-pc-bin

      - name: Build ISO
        run: |
          echo "Building cheeseDOS ISO"
          mkdir -p out
          echo "cheeseDOS ISO content" > out/cheeseDOS.txt
          xorriso -as mkisofs -o out/cheeseDOS.iso out/cheeseDOS.txt

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheeseDOS-iso
          path: out/cheeseDOS.iso

      - name: Create GitHub Release and Upload ISO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="arun-$(date +%Y%m%d%H%M%S)"
          RELEASE_NAME="cheeseDOS alpha"
          gh release create "$TAG" ./out/cheeseDOS.iso --title "$RELEASE_NAME" --notes "Rolling alpha cheeseDOS builds"
