name: Build and Release cheeseDOS ISO

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso grub-pc-bin

      - name: Build ISO
        run: |
          echo "Building cheeseDOS ISO"
          mkdir -p out
          touch out/cheeseDOS.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheeseDOS-iso
          path: out/cheeseDOS.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: arun ${{ github.run_number }}
          name: cheeseDOS alpha
          files: ./out/cheeseDOS.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
