name: Build and Release cheeseDOS ISO

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-multilib \
            grub-pc-bin \
            xorriso \
            mtools

      - name: Build ISO using Makefile
        run: make

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheeseDOS-iso
          path: cdos.iso

      - name: Create GitHub Release and Upload ISO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="auto-$(date +%Y%m%d%H%M%S)"
          RELEASE_NAME="cheeseDOS alpha"
          gh release create "$TAG" cdos.iso --title "$RELEASE_NAME" --notes "Rolling alpha cheeseDOS builds"
